version: '3.7'

services:
  schedules_db:
    image: postgres
    container_name: schedules_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=schedules_db
    volumes:
      - pgdata:/data/postgres
  api:
    build: .
    container_name: schedule_backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - schedules_db
    depends_on:
      - schedules_db
volumes:
  pgdata:
    driver: local
